"""
ASR Evaluation Script — Person 5
==================================
Tests faster-whisper on Arabic audio samples generated by test_tts.py.
Run AFTER test_tts.py has produced audio files.

Usage:
    cd backend
    python tests/test_asr.py ../../audio_outputs/tts_ar_LB_male.mp3

First run downloads the Whisper large-v3 model (~1.5 GB). Be on WiFi.
Document your findings in docs/asr_evaluation.md.
"""
import json
import os
import sys
import time
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))


def transcribe_and_report(audio_path: str, language: str = 'ar'):
    from faster_whisper import WhisperModel

    print(f'Loading Whisper large-v3 (first run downloads ~1.5 GB)...')
    model = WhisperModel('large-v3', device='cpu', compute_type='int8')
    print(f'Model ready. Transcribing: {audio_path}\n')

    t0 = time.time()
    segments_iter, info = model.transcribe(
        audio_path,
        language=language,
        task='transcribe',
        word_timestamps=True,
        vad_filter=True,
        vad_parameters={'min_silence_duration_ms': 500}
    )

    full_text = ''
    all_segments = []
    for seg in segments_iter:
        seg_data = {
            'start': round(seg.start, 2),
            'end': round(seg.end, 2),
            'text': seg.text.strip(),
            'words': [
                {
                    'word': w.word,
                    'start': round(w.start, 2),
                    'end': round(w.end, 2),
                    'prob': round(w.probability, 3)
                }
                for w in (seg.words or [])
            ]
        }
        all_segments.append(seg_data)
        full_text += seg.text + ' '

    elapsed = time.time() - t0
    full_text = full_text.strip()

    print('=== TRANSCRIPT ===')
    print(full_text)
    print('\n=== WORD TIMESTAMPS ===')
    for seg in all_segments:
        print(f"[{seg['start']}s–{seg['end']}s] {seg['text']}")
        for w in seg['words']:
            flag = '⚠️ ' if w['prob'] < 0.6 else ''
            print(f"    {flag}{w['word']}  ({w['prob']})")

    print('\n=== METADATA ===')
    print(f"Language detected : {info.language} (confidence {round(info.language_probability,2)})")
    print(f"Audio duration    : {round(info.duration, 1)}s")
    print(f"Transcription time: {round(elapsed, 1)}s")
    print(f"Speed ratio       : {round(info.duration / elapsed, 1)}x real-time")

    # Save JSON
    output = {
        'audio_file': audio_path,
        'full_text': full_text,
        'language_detected': info.language,
        'language_confidence': round(info.language_probability, 3),
        'duration_seconds': round(info.duration, 1),
        'transcription_time_seconds': round(elapsed, 1),
        'speed_ratio': round(info.duration / elapsed, 1),
        'segments': all_segments
    }
    json_path = audio_path.rsplit('.', 1)[0] + '_transcript.json'
    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f'\nJSON saved → {json_path}')
    print('\nNow copy your findings into docs/asr_evaluation.md')


if __name__ == '__main__':
    path = sys.argv[1] if len(sys.argv) > 1 else '../../audio_outputs/tts_ar_LB_male.mp3'
    lang = sys.argv[2] if len(sys.argv) > 2 else 'ar'
    transcribe_and_report(path, lang)
